# Generated by Django 4.1.7 on 2023-02-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_name_comment_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='mensaje',
        ),
    ]
