# Generated by Django 4.1.7 on 2023-02-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="titile",
            new_name="title",
        ),
    ]
