# Generated by Django 4.1.7 on 2023-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_rename_titile_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="blog/static/image"),
        ),
    ]
